/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/ai/bpmn/feedback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit feedback on a generated BPMN draft */
    post: operations["submit_bpmn_feedback_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/bpmn/regenerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Regenerate BPMN draft incorporating feedback */
    post: operations["regenerate_bpmn_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/transcribe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transcribe audio from business analyst-stakeholder interviews */
    post: operations["transcribe_audio_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/transcript-to-bpmn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate BPMN draft from interview transcript */
    post: operations["generate_bpmn_from_transcript_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bpm/verify/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify both structural and behavioral properties of a BPMN process */
    post: operations["verify_all_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bpm/verify/behavioral": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify behavioral properties of a BPMN process */
    post: operations["verify_behavioral_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bpm/verify/business": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify business properties of a BPMN process using AI */
    post: operations["verify_business_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/bpm/verify/structural": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Verify structural properties of a BPMN process */
    post: operations["verify_structural_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/context/graphs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate graph data for visualization */
    post: operations["context_graphs_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/context/summarize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Summarize context (automata, formulas, controllers) */
    post: operations["context_summarize_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/context/synthesize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Synthesize controller from ctxdsl specification */
    post: operations["context_synthesize_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check endpoint */
    get: operations["health_check"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/process/context/event-logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Suggest event log mappings for process instrumentation */
    post: operations["suggest_event_logs_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/process/context/extract-ir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Extract IR from process summary */
    post: operations["extract_ir_from_summary_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/process/context/pipeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Process use context through full pipeline (summarize + event logs + IR extraction) */
    post: operations["process_context_pipeline_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/process/context/summarize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Summarize use context into a structured process summary */
    post: operations["summarize_use_context_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Translate BPMN file to ctxdsl format */
    post: operations["translate_bpm_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm/async": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start an async translation job */
    post: operations["async_translate_bpm_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Translate multiple BPMN files in batch */
    post: operations["batch_translate_bpm_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm/ir": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Extract IR (Intermediate Representation) from BPMN without translation.
     * @description This endpoint returns only the IR model, without performing CLTS translation.
     *     Useful for debugging, tooling integration, and understanding the IR structure.
     */
    post: operations["extract_ir_handler"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm/result/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the result of a completed translation job */
    get: operations["get_translation_result_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/translate/bpm/status/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the status of a translation job */
    get: operations["get_translation_status_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccessControlApi: {
      audit_logging: boolean;
      encryption_required: boolean;
      roles: string[];
    };
    ActorApi: {
      description?: string | null;
      name: string;
      role: string;
    };
    ApiEndpointConfigApi: {
      endpoint: string;
      method: string;
    };
    ArtifactConfigApi: {
      access_control?: null | components["schemas"]["AccessControlApi"];
      fields: components["schemas"]["LogFieldApi"][];
      retention: components["schemas"]["RetentionPolicyApi"];
    };
    /** @description Artifact type for API (serialized as single-key object) */
    ArtifactTypeApi:
      | {
          DatabaseTable: components["schemas"]["DatabaseTableConfigApi"];
        }
      | {
          LogFile: components["schemas"]["LogFileConfigApi"];
        }
      | {
          MessageQueue: components["schemas"]["MessageQueueConfigApi"];
        }
      | {
          ApiEndpoint: components["schemas"]["ApiEndpointConfigApi"];
        }
      | {
          CloudService: components["schemas"]["CloudServiceConfigApi"];
        }
      | {
          Custom: components["schemas"]["CustomConfigApi"];
        };
    AssumptionApi: {
      assumption: string;
      impact: string;
      reason: string;
    };
    /** @description Response from starting an async translation job */
    AsyncTranslationResponse: {
      job_id: string;
      message: string;
      status: string;
    };
    /**
     * @description Supported audio formats
     * @enum {string}
     */
    AudioFormat: "mp3" | "wav" | "m4a" | "webm" | "ogg";
    /** @description Audio input for transcription */
    AudioInput: {
      /** @description Base64-encoded audio data */
      content: string;
      /** @description Audio format */
      format: components["schemas"]["AudioFormat"];
      /** @description Language code (ISO 639-1, e.g., "en", "es", "de") */
      language?: string | null;
      /**
       * Format: int32
       * @description Sample rate in Hz (optional, defaults to 16000)
       */
      sample_rate?: number;
    };
    /** @description Automaton summary information */
    AutomatonSummary: {
      name: string;
      states_count: number;
      transitions_count: number;
    };
    /** @description Request for batch translation of multiple BPMN files */
    BatchTranslateBpmRequest: {
      files: components["schemas"]["BpmnInput"][];
      options?: components["schemas"]["TranslateOptions"];
    };
    /** @description Response from batch translation */
    BatchTranslateBpmResponse: {
      failed: number;
      results: components["schemas"]["BatchTranslationResult"][];
      successful: number;
      total: number;
    };
    /** @description Result for a single file in batch translation */
    BatchTranslationResult: {
      error?: string | null;
      filename: string;
      index: number;
      success: boolean;
      translation?: null | components["schemas"]["TranslateBpmResponse"];
    };
    /** @description API representation of behavioral check result */
    BehavioralCheckResultApi: {
      check_name: string;
      counterexample?: null | components["schemas"]["CounterexampleApi"];
      evidence: string;
      /** @description Suggestions for fixing violations (always included) */
      fix_suggestions: string[];
      formula: string;
      satisfied: boolean;
      satisfying_states: string[];
      violating_states: string[];
    };
    /** @description Request for behavioral property verification */
    BehavioralVerificationRequest: {
      bpmn: components["schemas"]["BpmnInput"];
      options?: components["schemas"]["VerificationOptions"];
    };
    /** @description Behavioral verification result */
    BehavioralVerificationResult: {
      all_satisfied: boolean;
      /** @description List of available checks with metadata */
      available_checks: components["schemas"]["CheckMetadataApi"][];
      /** @description Results of running the checks */
      checks: components["schemas"]["BehavioralCheckResultApi"][];
      violation_count: number;
    };
    /**
     * @description BPMN Intermediate Representation (IR) for API serialization.
     *
     *     This is a serializable representation of the IR model that can be included
     *     in API responses. It mirrors the structure of `BpmModel` but with all fields
     *     serializable to JSON.
     */
    BpmIr: {
      message_flows: components["schemas"]["BpmIrMessageFlow"][];
      name: string;
      properties: components["schemas"]["BpmIrProperty"][];
      states: components["schemas"]["BpmIrState"][];
      transitions: components["schemas"]["BpmIrTransition"][];
      variables: components["schemas"]["BpmIrVariable"][];
    };
    /** @description IR effect representation */
    BpmIrEffect: {
      value: unknown;
      variable: string;
    };
    /** @description IR message flow representation */
    BpmIrMessageFlow: {
      id: string;
      name?: string | null;
      source_ref?: string | null;
      target_ref?: string | null;
    };
    /** @description IR property representation */
    BpmIrProperty: {
      formula: string;
      kind?: string | null;
      name: string;
    };
    /** @description IR state representation */
    BpmIrState: {
      attached_to?: string | null;
      event_kinds: string[];
      initial: boolean;
      is_for_compensation: boolean;
      kind?: string | null;
      name: string;
      role?: string | null;
    };
    /** @description IR transition representation */
    BpmIrTransition: {
      effects: components["schemas"]["BpmIrEffect"][];
      from: string;
      guard?: string | null;
      label: string;
      to: string;
    };
    /** @description IR variable representation */
    BpmIrVariable: {
      initial?: unknown;
      name: string;
      ty: string;
    };
    /** @description Correction to a BPMN draft */
    BpmnCorrection: {
      /** @description Optional corrected element data (for name/description changes) */
      corrected_data?: unknown;
      /** @description Optional corrected BPMN XML fragment (for structural changes) */
      corrected_xml?: string | null;
      /** @description Type of correction */
      correction_type: components["schemas"]["CorrectionType"];
      /** @description Description of what needs to be changed */
      description: string;
      /** @description Target element (process ID, role ID, or task/gateway ID) */
      target_element: string;
    };
    /** @description BPMN draft structure */
    BpmnDraft: {
      processes: components["schemas"]["BpmnProcessDraft"][];
      roles: components["schemas"]["BpmnRoleDraft"][];
      xml: string;
    };
    /** @description Request to submit feedback on a BPMN draft */
    BpmnFeedbackRequest: {
      /** @description BPMN draft ID to provide feedback on */
      bpmn_draft_id: string;
      /** @description Optional general feedback comments */
      comments?: string | null;
      /** @description User corrections and edits */
      corrections: components["schemas"]["BpmnCorrection"][];
    };
    /** @description Response from feedback submission */
    BpmnFeedbackResponse: {
      /** @description BPMN draft ID this feedback applies to */
      bpmn_draft_id: string;
      /** @description Number of corrections submitted */
      corrections_count: number;
      /** @description Feedback ID for tracking */
      feedback_id: string;
      /** @description Timestamp when feedback was submitted */
      submitted_at: string;
      /** @description Version number after this feedback */
      version: number;
    };
    /**
     * @description BPMN format type
     * @enum {string}
     */
    BpmnFormat: "xml" | "json";
    /** @description BPMN generation context */
    BpmnGenerationContext: {
      /** @description Business domain */
      domain: string;
      /** @description Existing processes to reference */
      existing_processes?: components["schemas"]["ProcessReference"][];
      /** @description Interview type */
      interview_type: components["schemas"]["InterviewType"];
      /** @description Locale string (e.g., "en-US", "es-ES") */
      locale?: string | null;
      /** @description Speaker hints for better role identification */
      speaker_hints?: components["schemas"]["SpeakerHints"];
      /** @description Optional transcript ID */
      transcript_id?: string | null;
    };
    /** @description BPMN generation metadata */
    BpmnGenerationMetadata: {
      extraction_model: string;
      processes_identified: number;
      /** Format: double */
      processing_time_seconds: number;
      roles_identified: number;
      segments_analyzed: number;
    };
    /** @description BPMN generation options */
    BpmnGenerationOptions: {
      /** @description BPMN version (default: "2.0") */
      bpmn_version?: string;
      /**
       * Format: double
       * @description Confidence threshold (0.0 to 1.0)
       */
      confidence_threshold?: number;
      /** @description Generate multiple processes if found */
      generate_multiple_processes?: boolean;
      /** @description Include annotations */
      include_annotations?: boolean;
      /** @description Include data objects */
      include_data_objects?: boolean;
      /** @description Include swimlanes */
      include_swimlanes?: boolean;
      /** @description Validation level */
      validation_level?: components["schemas"]["ValidationLevel"];
    };
    /** @description Request for BPMN generation from transcript */
    BpmnGenerationRequest: {
      context: components["schemas"]["BpmnGenerationContext"];
      options?: components["schemas"]["BpmnGenerationOptions"];
      transcript: components["schemas"]["Transcript"];
    };
    /** @description Response from BPMN generation */
    BpmnGenerationResponse: {
      bpmn: components["schemas"]["BpmnDraft"];
      bpmn_draft_id: string;
      metadata: components["schemas"]["BpmnGenerationMetadata"];
      validation: components["schemas"]["BpmnValidationResult"];
    };
    /** @description BPMN input content */
    BpmnInput: {
      content: string;
      format: components["schemas"]["BpmnFormat"];
    };
    /** @description BPMN process draft */
    BpmnProcessDraft: {
      /** Format: double */
      confidence: number;
      description: string;
      id: string;
      name: string;
      source_segments: string[];
    };
    /** @description Request to regenerate BPMN with feedback incorporated */
    BpmnRegenerateRequest: {
      /** @description Optional additional corrections to apply */
      additional_corrections?: components["schemas"]["BpmnCorrection"][];
      /** @description Original BPMN draft ID */
      bpmn_draft_id: string;
      /** @description BPMN generation context */
      context: components["schemas"]["BpmnGenerationContext"];
      /** @description Optional feedback ID(s) to incorporate (if not provided, uses most recent) */
      feedback_ids?: string[];
      /** @description Original transcript (required for re-generation) */
      transcript: components["schemas"]["Transcript"];
    };
    /** @description Response from BPMN regeneration */
    BpmnRegenerateResponse: {
      /** @description Generated BPMN draft */
      bpmn: components["schemas"]["BpmnDraft"];
      /** @description New BPMN draft ID */
      bpmn_draft_id: string;
      /** @description Improvements made based on feedback */
      improvements: string[];
      /** @description Generation metadata */
      metadata: components["schemas"]["BpmnGenerationMetadata"];
      /** @description Previous BPMN draft ID */
      previous_bpmn_draft_id: string;
      /** @description Validation results */
      validation: components["schemas"]["BpmnValidationResult"];
      /** @description Version number */
      version: number;
    };
    /** @description BPMN role draft */
    BpmnRoleDraft: {
      /** Format: double */
      confidence: number;
      description: string;
      id: string;
      name: string;
      source_segments: string[];
    };
    /** @description BPMN validation result */
    BpmnValidationResult: {
      consistency_checks: components["schemas"]["ConsistencyChecks"];
      errors: components["schemas"]["ValidationError"][];
      schema_valid: boolean;
      syntactically_valid: boolean;
      warnings: components["schemas"]["ValidationWarning"][];
    };
    /** @description Version history entry for a BPMN draft */
    BpmnVersionHistory: {
      /** @description BPMN draft ID */
      bpmn_draft_id: string;
      /** @description Summary of changes in this version */
      changes_summary: string[];
      /** @description Timestamp when this version was created */
      created_at: string;
      /** @description Feedback IDs that led to this version */
      feedback_ids: string[];
      /** @description Parent version (None for original) */
      parent_version?: number | null;
      /** @description Version number */
      version: number;
    };
    BudgetContextApi: {
      /** Format: double */
      amount: number;
      constraints?: string | null;
      currency: string;
      period: string;
    };
    /** @description API representation of business rule violation */
    BusinessRuleViolationApi: {
      description: string;
      location: string[];
      rule_name: string;
      severity: string;
      suggested_fix?: string | null;
    };
    /** @description Request for business property verification */
    BusinessVerificationRequest: {
      bpmn: components["schemas"]["BpmnInput"];
      /** @description Business domain (e.g., "finance", "healthcare", "manufacturing") */
      domain: string;
      /** @description Optional locale string (e.g., "en-US", "es-ES", "de-DE") for culturally-aware analysis */
      locale?: string | null;
      options?: components["schemas"]["VerificationOptions"];
      summary?: null | components["schemas"]["ProcessSummaryApi"];
      use_context?: null | components["schemas"]["UseContextApi"];
    };
    /** @description Business verification result */
    BusinessVerificationResult: {
      compliant: boolean;
      domain: string;
      notes: string[];
      property_suggestions: components["schemas"]["PropertySuggestionApi"][];
      violations: components["schemas"]["BusinessRuleViolationApi"][];
    };
    /** @description Check metadata for API responses */
    CheckMetadataApi: {
      check_name: string;
      description: string;
      severity: string;
    };
    /**
     * @description Cleanup aggressiveness level
     * @enum {string}
     */
    CleanupAggressiveness: "light" | "moderate" | "aggressive";
    CloudServiceConfigApi: {
      resource: string;
      service: string;
    };
    /** @description Request for combined property verification */
    CombinedVerificationRequest: {
      bpmn: components["schemas"]["BpmnInput"];
      options?: components["schemas"]["VerificationOptions"];
    };
    /** @description Consistency checks */
    ConsistencyChecks: {
      event_naming_consistent: boolean;
      role_naming_consistent: boolean;
      symbol_usage_consistent: boolean;
    };
    /** @description Request for graph generation */
    ContextGraphsRequest: {
      automaton?: string | null;
      context: components["schemas"]["FileContent"];
      graph_types?: components["schemas"]["GraphType"][];
      sidecars?: components["schemas"]["SidecarFile"][];
    };
    /** @description Response from graph generation */
    ContextGraphsResponse: {
      context: components["schemas"]["ContextSummary"];
      graphs: components["schemas"]["GraphData"][];
      success: boolean;
    };
    /** @description Request for context summarization */
    ContextSummarizeRequest: {
      context: components["schemas"]["FileContent"];
      format?: components["schemas"]["SummarizeFormat"];
      sidecars?: components["schemas"]["SidecarFile"][];
    };
    /** @description Response from context summarization */
    ContextSummarizeResponse: {
      success: boolean;
      summary: components["schemas"]["ContextSummary"];
    };
    /** @description Context summary information */
    ContextSummary: {
      automata: components["schemas"]["AutomatonSummary"][];
      context_name: string;
      controllers_count: number;
      formulas_count: number;
    };
    /** @description Request for controller synthesis */
    ContextSynthesizeRequest: {
      automaton: string;
      context: components["schemas"]["FileContent"];
      formula: string;
      options?: components["schemas"]["SynthesisOptions"];
      sidecars?: components["schemas"]["SidecarFile"][];
    };
    /** @description Response from controller synthesis */
    ContextSynthesizeResponse: {
      controller?: null | components["schemas"]["FileContent"];
      diagnostics: components["schemas"]["SynthesisDiagnostics"];
      realizable: boolean;
      success: boolean;
    };
    /**
     * @description Type of correction
     * @enum {string}
     */
    CorrectionType:
      | "process_name"
      | "process_structure"
      | "role_name"
      | "missing_element"
      | "incorrect_element"
      | "missing_flow"
      | "incorrect_flow"
      | "other";
    CostEstimateApi: {
      breakdown: components["schemas"]["CostItemApi"][];
      currency: string;
      /** Format: double */
      monthly_operational_cost: number;
      /** Format: double */
      setup_cost: number;
    };
    CostItemApi: {
      /** Format: double */
      cost: number;
      frequency: string;
      item: string;
    };
    /** @description API representation of counterexample */
    CounterexampleApi: {
      description: string;
      trace: string[];
    };
    CustomConfigApi: {
      description: string;
      name: string;
    };
    DatabaseTableConfigApi: {
      schema: string;
      table_name: string;
    };
    DecisionPointApi: {
      condition?: string | null;
      description: string;
      outcomes: string[];
    };
    DesignNoteApi: {
      decision: string;
      element_id: string;
      element_type: string;
      justification: string;
      source_reference?: string | null;
    };
    /** @description Diagnostics options */
    DiagnosticsOptions: {
      counterexample?: boolean;
      counterstrategy?: boolean;
      deadlock_traces?: boolean;
      /** Format: int32 */
      max_counter_traces?: number | null;
    };
    DigitalizationContextApi: {
      available_tools?: string[];
      constraints?: string[];
      current_efforts: string;
      /** Format: double */
      current_level: number;
      /** Format: double */
      target_level?: number | null;
    };
    /** @description Error detail for API responses */
    ErrorDetail: {
      code: string;
      details?: string | null;
      message: string;
    };
    /** @description Standard error response */
    ErrorResponse: {
      error: components["schemas"]["ErrorDetail"];
      success: boolean;
    };
    EventLogMetadataApi: {
      events_mapped: number;
      infrastructure_components: number;
      model_used: string;
      /** Format: double */
      processing_time_seconds: number;
    };
    /** @description Options for event log suggestions */
    EventLogOptions: {
      include_cost_estimates?: boolean;
      min_priority?: string | null;
      prioritize_by?: string | null;
    };
    EventLogSuggestionsApi: {
      estimated_cost?: null | components["schemas"]["CostEstimateApi"];
      event_mappings: components["schemas"]["EventMappingApi"][];
      infrastructure: components["schemas"]["LoggingInfrastructureApi"];
      metadata: components["schemas"]["EventLogMetadataApi"];
    };
    /** @description Request for event log suggestions */
    EventLogSuggestionsRequest: {
      /**
       * Format: int32
       * @description Iteration number (1-based). If None, this is the initial iteration.
       */
      iteration_number?: number | null;
      options?: components["schemas"]["EventLogOptions"];
      prior_results?: null | components["schemas"]["PriorResults"];
      summary?: null | components["schemas"]["ProcessSummaryApi"];
      summary_id?: string | null;
      use_context: components["schemas"]["UseContextApi"];
    };
    /** @description Response from event log suggestions */
    EventLogSuggestionsResponse: {
      /**
       * Format: int32
       * @description Iteration number (1-based). 1 for initial iteration.
       */
      iteration_number: number;
      suggestions: components["schemas"]["EventLogSuggestionsApi"];
      suggestions_id: string;
    };
    EventMappingApi: {
      artifact_config: components["schemas"]["ArtifactConfigApi"];
      artifact_type: components["schemas"]["ArtifactTypeApi"];
      /** Format: double */
      cost_estimate?: number | null;
      description: string;
      event_name: string;
      priority: components["schemas"]["PriorityApi"];
      source: string;
    };
    /** @description Request for IR extraction from summary */
    ExtractIrFromSummaryRequest: {
      event_log_suggestions?:
        | null
        | components["schemas"]["EventLogSuggestionsApi"];
      /**
       * Format: int32
       * @description Iteration number (1-based). If None, this is the initial iteration.
       */
      iteration_number?: number | null;
      options?: components["schemas"]["IrExtractionOptions"];
      prior_results?: null | components["schemas"]["PriorResults"];
      summary: components["schemas"]["ProcessSummaryApi"];
      use_context: components["schemas"]["UseContextApi"];
    };
    /** @description Response from IR extraction */
    ExtractIrFromSummaryResponse: {
      bpmn_xml?: string | null;
      extraction_id: string;
      /**
       * Format: int32
       * @description Iteration number (1-based). 1 for initial iteration.
       */
      iteration_number: number;
      result: components["schemas"]["IrExtractionResultApi"];
    };
    /** @description File content with optional name */
    FileContent: {
      content: string;
      name: string;
    };
    /** @description Graph data with metadata */
    GraphData: {
      automaton: string;
      elements: components["schemas"]["GraphElement"][];
      graph_type: components["schemas"]["GraphTypeResponse"];
      metadata: components["schemas"]["GraphMetadata"];
    };
    /** @description Graph element (node or edge) for visualization */
    GraphElement: {
      classes?: string | null;
      data: components["schemas"]["GraphElementData"];
      position?: null | components["schemas"]["GraphPosition"];
    };
    /** @description Graph element data (node or edge) */
    GraphElementData:
      | {
          actions?: string[];
          id: string;
          label: string;
          parent?: string | null;
          /** @enum {string} */
          type: "node";
          vars?: string[];
        }
      | {
          action?: string | null;
          action_type?: string | null;
          effect?: string | null;
          guard?: string | null;
          id: string;
          label?: string | null;
          source: string;
          target: string;
          /** @enum {string} */
          type: "edge";
        };
    /** @description Graph metadata */
    GraphMetadata: {
      initial_states?: string[];
      states_count: number;
      transitions_count: number;
    };
    /** @description Graph position coordinates */
    GraphPosition: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    /**
     * @description Graph type
     * @enum {string}
     */
    GraphType: "dsl" | "unrolled";
    /**
     * @description Graph type in response (serialized as string)
     * @enum {string}
     */
    GraphTypeResponse: "dsl" | "unrolled";
    InfrastructureComponentApi: {
      component_type: string;
      description: string;
      name: string;
      required: boolean;
    };
    /**
     * @description Interview type
     * @enum {string}
     */
    InterviewType:
      | "process_discovery"
      | "process_improvement"
      | "compliance_review";
    IrExtractionMetadataApi: {
      design_notes_count: number;
      /** @description List of changes detected compared to prior IR (e.g., ["state_added", "transition_renamed", "variable_removed"]) */
      ir_changes?: string[];
      labels_extracted: number;
      model_used: string;
      /** @description ID of prior IR extraction if this is an iteration */
      prior_ir_id?: string | null;
      /** Format: double */
      processing_time_seconds: number;
      states_extracted: number;
      transitions_extracted: number;
      variables_extracted: number;
    };
    /** @description Options for IR extraction */
    IrExtractionOptions: {
      include_assumptions?: boolean;
      include_design_notes?: boolean;
      validation_level?: string | null;
    };
    IrExtractionResultApi: {
      assumptions?: components["schemas"]["AssumptionApi"][];
      /** Format: double */
      confidence: number;
      design_notes: components["schemas"]["DesignNoteApi"][];
      ir_model: components["schemas"]["BpmIr"];
      metadata: components["schemas"]["IrExtractionMetadataApi"];
    };
    /** @description Response for job status query */
    JobStatusResponse: {
      /** @description Timestamp when the job was created (ISO 8601 format) */
      created_at: string;
      error?: string | null;
      job_id: string;
      result?: null | components["schemas"]["TranslateBpmResponse"];
      status: string;
      /** @description Timestamp when the job was last updated (ISO 8601 format) */
      updated_at: string;
    };
    LogFieldApi: {
      data_type: string;
      description?: string | null;
      name: string;
      required: boolean;
    };
    LogFileConfigApi: {
      format: string;
      path: string;
    };
    LoggingInfrastructureApi: {
      /** Format: double */
      compatibility_score: number;
      /** Format: int32 */
      complexity: number;
      components: components["schemas"]["InfrastructureComponentApi"][];
    };
    MessageQueueConfigApi: {
      broker: string;
      queue_name: string;
    };
    /** @description Minimization report */
    MinimizationReport: {
      merged_states?: string[];
      removed_states: number;
      removed_transitions: number;
    };
    /** @description Options for pipeline processing */
    PipelineOptions: {
      event_log_options?: null | components["schemas"]["EventLogOptions"];
      include_event_logs?: boolean;
      include_ir_extraction?: boolean;
      include_summarization?: boolean;
      ir_extraction_options?:
        | null
        | components["schemas"]["IrExtractionOptions"];
      summarize_options?: null | components["schemas"]["SummarizeOptions"];
    };
    /** @description Prior results from previous iterations for context */
    PriorResults: {
      /** @description Failed structural tests from previous iteration */
      failed_structural_tests?: string[] | null;
      prior_ir?: null | components["schemas"]["IrExtractionResultApi"];
      prior_summary?: null | components["schemas"]["ProcessSummaryApi"];
      /** @description Prior business rule violations from previous iteration */
      prior_violations?:
        | components["schemas"]["BusinessRuleViolationApi"][]
        | null;
    };
    /** @enum {string} */
    PriorityApi: "critical" | "high" | "medium" | "low";
    /** @description Request for full pipeline (summarize + event logs + IR extraction) */
    ProcessContextPipelineRequest: {
      /**
       * Format: int32
       * @description Iteration number (1-based). If None, this is the initial iteration.
       */
      iteration_number?: number | null;
      options?: components["schemas"]["PipelineOptions"];
      prior_results?: null | components["schemas"]["PriorResults"];
      use_context: components["schemas"]["UseContextApi"];
    };
    /** @description Response from pipeline processing */
    ProcessContextPipelineResponse: {
      event_log_suggestions?:
        | null
        | components["schemas"]["EventLogSuggestionsApi"];
      ir_extraction?: null | components["schemas"]["IrExtractionResultApi"];
      /**
       * Format: int32
       * @description Iteration number (1-based). 1 for initial iteration.
       */
      iteration_number: number;
      pipeline_id: string;
      summary?: null | components["schemas"]["ProcessSummaryApi"];
      /** Format: double */
      total_time_seconds: number;
    };
    /** @description Reference to an existing process */
    ProcessReference: {
      description: string;
      name: string;
    };
    ProcessReferenceApi: {
      identifier: string;
      notes?: string | null;
      status?: string | null;
      type: string;
    };
    ProcessSummaryApi: {
      actors: components["schemas"]["ActorApi"][];
      /** Format: double */
      confidence: number;
      decision_points: components["schemas"]["DecisionPointApi"][];
      exceptions?: string[];
      metadata: components["schemas"]["SummaryMetadataApi"];
      summary: string;
      terminology?: components["schemas"]["TermDefinitionApi"][];
    };
    /** @description Proof obligation */
    ProofObligation: {
      detail?: string | null;
      state: string;
    };
    /** @description API representation of property suggestion */
    PropertySuggestionApi: {
      category: string;
      /** Format: double */
      confidence: number;
      description: string;
      formula: string;
      name: string;
      rationale: string;
      related_elements?: string[];
    };
    QAExchangeApi: {
      answer: string;
      follow_ups?: string[];
      question: string;
      /** Format: double */
      timestamp?: number | null;
    };
    QASessionApi: {
      exchanges: components["schemas"]["QAExchangeApi"][];
    };
    /** @description Removed content metadata */
    RemovedContent: {
      filler_words: string[];
      off_topic_phrases: string[];
      redundant_repetitions: number;
    };
    RetentionPolicyApi: {
      /** Format: int32 */
      archive_after_days?: number | null;
      compliance_requirements?: string[];
      /** Format: int32 */
      duration_days?: number | null;
    };
    /** @description Sidecar file content */
    SidecarFile: {
      content: string;
      name: string;
    };
    /** @description Speaker hints for BPMN generation */
    SpeakerHints: {
      /** @description Phrases that indicate analyst speech */
      analyst_indicators?: string[];
      /** @description Phrases that indicate stakeholder speech */
      stakeholder_indicators?: string[];
    };
    /** @description Speaker information */
    SpeakerInfo: {
      /** Format: double */
      confidence: number;
      segments: string[];
      /** Format: double */
      total_time_seconds: number;
    };
    /** @description Speaker summary */
    SpeakerSummary: {
      analyst?: null | components["schemas"]["SpeakerInfo"];
      stakeholder?: null | components["schemas"]["SpeakerInfo"];
    };
    /**
     * @description Speaker type
     * @enum {string}
     */
    SpeakerType: "analyst" | "stakeholder" | "unknown";
    /** @description API representation of structural check result */
    StructuralCheckResultApi: {
      check_name: string;
      evidence: string;
      location: string[];
      passed: boolean;
      severity: string;
      suggestions?: string[];
    };
    /** @description Request for structural property verification */
    StructuralVerificationRequest: {
      bpmn: components["schemas"]["BpmnInput"];
      options?: components["schemas"]["VerificationOptions"];
    };
    /** @description Structural verification result */
    StructuralVerificationResult: {
      all_passed: boolean;
      /** @description List of available checks with metadata */
      available_checks: components["schemas"]["CheckMetadataApi"][];
      /** @description Results of running the checks */
      checks: components["schemas"]["StructuralCheckResultApi"][];
      error_count: number;
      info_count: number;
      warning_count: number;
    };
    /**
     * @description Summary output format
     * @enum {string}
     */
    SummarizeFormat: "json" | "table";
    /** @description Options for summarization */
    SummarizeOptions: {
      include_exceptions?: boolean;
      include_terminology?: boolean;
      target_audience?: string | null;
    };
    /** @description Request for use context summarization */
    SummarizeUseContextRequest: {
      /**
       * Format: int32
       * @description Iteration number (1-based). If None, this is the initial iteration.
       */
      iteration_number?: number | null;
      options?: components["schemas"]["SummarizeOptions"];
      prior_results?: null | components["schemas"]["PriorResults"];
      use_context: components["schemas"]["UseContextApi"];
    };
    /** @description Response from use context summarization */
    SummarizeUseContextResponse: {
      /**
       * Format: int32
       * @description Iteration number (1-based). 1 for initial iteration.
       */
      iteration_number: number;
      summary: components["schemas"]["ProcessSummaryApi"];
      summary_id: string;
    };
    SummaryMetadataApi: {
      /** Format: double */
      compression_ratio: number;
      model_used: string;
      /** @description ID of prior summary if this is an iteration */
      prior_summary_id?: string | null;
      /** Format: double */
      processing_time_seconds: number;
      source_length: number;
      /** @description List of changes detected compared to prior summary (e.g., ["actor_added", "decision_point_updated"]) */
      summary_changes?: string[];
      summary_length: number;
    };
    /** @description Synthesis diagnostics (matches ControllerDiagnostics structure) */
    SynthesisDiagnostics: {
      counterexample_trace?: string[] | null;
      counterstrategy_traces?: string[][];
      deadlock_traces?: string[][];
      messages?: string[];
      minimization?: null | components["schemas"]["MinimizationReport"];
      proof_obligations?: components["schemas"]["ProofObligation"][];
      violating_initials?: string[];
    };
    /** @description Synthesis options */
    SynthesisOptions: {
      diagnostics?: components["schemas"]["DiagnosticsOptions"];
      minimize?: boolean;
    };
    TermDefinitionApi: {
      definition: string;
      term: string;
    };
    /**
     * @description Text formatting style
     * @enum {string}
     */
    TextFormatting: "paragraphs" | "sentences" | "raw";
    /** @description Transcript structure */
    Transcript: {
      /** @description Cleaned, process-focused full text */
      full_text: string;
      /** @description Metadata */
      metadata: components["schemas"]["TranscriptMetadata"];
      /** @description Original transcription before cleanup */
      raw_full_text: string;
      /** @description Transcript segments */
      segments: components["schemas"]["TranscriptSegment"][];
    };
    /** @description Transcript metadata */
    TranscriptMetadata: {
      cleaned_word_count: number;
      cleanup_applied: boolean;
      cleanup_model?: string | null;
      /** Format: double */
      duration_seconds: number;
      language_detected: string;
      original_word_count: number;
      /** Format: double */
      reduction_percentage: number;
      speaker_count: number;
      transcription_model: string;
    };
    /** @description Transcript segment */
    TranscriptSegment: {
      cleaned: boolean;
      /** Format: double */
      confidence: number;
      /** Format: double */
      end_time: number;
      id: string;
      /** @description Original transcription before cleanup */
      raw_text: string;
      removed_content?: null | components["schemas"]["RemovedContent"];
      speaker: components["schemas"]["SpeakerType"];
      /** Format: double */
      speaker_confidence: number;
      /** Format: double */
      start_time: number;
      /** @description Cleaned text */
      text: string;
    };
    /** @description Transcription context */
    TranscriptionContext: {
      /** @description Optional analyst name */
      analyst_name?: string | null;
      /** @description Business domain */
      domain: string;
      /**
       * @description Optional BPMN file content (XML) to use as a starting point/reference
       *     This helps guide transcription, speaker identification, and cleanup when
       *     the interview is about improving or reviewing an existing process
       */
      existing_bpmn?: string | null;
      /** @description Type of interview */
      interview_type: components["schemas"]["InterviewType"];
      /** @description Locale string (e.g., "en-US", "es-ES") */
      locale?: string | null;
      /** @description Optional stakeholder name */
      stakeholder_name?: string | null;
    };
    /** @description Transcription options */
    TranscriptionOptions: {
      /** @description Cleanup aggressiveness level */
      cleanup_aggressiveness?: components["schemas"]["CleanupAggressiveness"];
      /** @description Enable transcript cleanup */
      enable_cleanup?: boolean;
      /** @description Enable confidence scores */
      enable_confidence_scores?: boolean;
      /** @description Enable speaker diarization */
      enable_speaker_diarization?: boolean;
      /** @description Enable timestamps */
      enable_timestamps?: boolean;
      /** @description Text formatting style */
      formatting?: components["schemas"]["TextFormatting"];
      /** @description Enable punctuation */
      punctuation?: boolean;
    };
    /** @description Request for audio transcription */
    TranscriptionRequest: {
      audio: components["schemas"]["AudioInput"];
      context: components["schemas"]["TranscriptionContext"];
      options?: components["schemas"]["TranscriptionOptions"];
    };
    /** @description Response from transcription */
    TranscriptionResponse: {
      speakers: components["schemas"]["SpeakerSummary"];
      transcript: components["schemas"]["Transcript"];
      transcript_id: string;
    };
    /** @description Request for BPMN translation */
    TranslateBpmRequest: {
      bpmn: components["schemas"]["BpmnInput"];
      options?: components["schemas"]["TranslateOptions"];
      sidecars?: components["schemas"]["SidecarFile"][];
    };
    /** @description Response from BPMN translation */
    TranslateBpmResponse: {
      errors?: string[];
      ir?: null | components["schemas"]["BpmIr"];
      metadata: components["schemas"]["TranslationMetadata"];
      output: components["schemas"]["TranslationOutput"];
      success: boolean;
      verification?: null | components["schemas"]["VerificationResponse"];
      warnings?: string[];
    };
    /** @description Translation options */
    TranslateOptions: {
      force?: boolean;
      /** @description Include IR (Intermediate Representation) in response */
      include_ir?: boolean;
      name?: string | null;
      verify?: null | components["schemas"]["VerificationOptions"];
    };
    /** @description Translation metadata */
    TranslationMetadata: {
      automata_count: number;
      context_name: string;
      sidecars_count: number;
    };
    /** @description Translation output files */
    TranslationOutput: {
      context: components["schemas"]["FileContent"];
      sidecars: components["schemas"]["FileContent"][];
    };
    /** @description Use context for API */
    UseContextApi: {
      budget?: null | components["schemas"]["BudgetContextApi"];
      digitalization?: null | components["schemas"]["DigitalizationContextApi"];
      domain: string;
      existing_process_reference?:
        | null
        | components["schemas"]["ProcessReferenceApi"];
      locale?: string | null;
      qa_session?: null | components["schemas"]["QASessionApi"];
      stakeholder_description: string;
    };
    /** @description Validation error */
    ValidationError: {
      error_type: string;
      message: string;
      process?: string | null;
    };
    /**
     * @description Validation level
     * @enum {string}
     */
    ValidationLevel: "strict" | "moderate" | "lenient";
    /** @description Validation warning */
    ValidationWarning: {
      message: string;
      process?: string | null;
      severity: string;
      warning_type: string;
    };
    /** @description Options for property verification */
    VerificationOptions: {
      /** @description Include detailed results for each check */
      detailed?: boolean;
      /** @description Include suggestions for fixing issues */
      include_suggestions?: boolean;
    };
    /** @description Response from property verification */
    VerificationResponse: {
      behavioral?: null | components["schemas"]["BehavioralVerificationResult"];
      errors?: string[];
      structural?: null | components["schemas"]["StructuralVerificationResult"];
      success: boolean;
      warnings?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  submit_bpmn_feedback_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BpmnFeedbackRequest"];
      };
    };
    responses: {
      /** @description Feedback submitted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BpmnFeedbackResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  regenerate_bpmn_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BpmnRegenerateRequest"];
      };
    };
    responses: {
      /** @description BPMN regenerated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BpmnRegenerateResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  transcribe_audio_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranscriptionRequest"];
      };
    };
    responses: {
      /** @description Transcription successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TranscriptionResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Payload too large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  generate_bpmn_from_transcript_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BpmnGenerationRequest"];
      };
    };
    responses: {
      /** @description BPMN generation successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BpmnGenerationResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  verify_all_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CombinedVerificationRequest"];
      };
    };
    responses: {
      /** @description Verification successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  verify_behavioral_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BehavioralVerificationRequest"];
      };
    };
    responses: {
      /** @description Behavioral verification successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  verify_business_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BusinessVerificationRequest"];
      };
    };
    responses: {
      /** @description Business verification successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BusinessVerificationResult"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  verify_structural_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StructuralVerificationRequest"];
      };
    };
    responses: {
      /** @description Structural verification successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  context_graphs_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContextGraphsRequest"];
      };
    };
    responses: {
      /** @description Graphs generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContextGraphsResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  context_summarize_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContextSummarizeRequest"];
      };
    };
    responses: {
      /** @description Summary generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContextSummarizeResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  context_synthesize_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContextSynthesizeRequest"];
      };
    };
    responses: {
      /** @description Synthesis completed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ContextSynthesizeResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  suggest_event_logs_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EventLogSuggestionsRequest"];
      };
    };
    responses: {
      /** @description Event log suggestions generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventLogSuggestionsResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  extract_ir_from_summary_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtractIrFromSummaryRequest"];
      };
    };
    responses: {
      /** @description IR extraction successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExtractIrFromSummaryResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  process_context_pipeline_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProcessContextPipelineRequest"];
      };
    };
    responses: {
      /** @description Pipeline processing successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProcessContextPipelineResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  summarize_use_context_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SummarizeUseContextRequest"];
      };
    };
    responses: {
      /** @description Summarization successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SummarizeUseContextResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  translate_bpm_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranslateBpmRequest"];
      };
    };
    responses: {
      /** @description Translation successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TranslateBpmResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  async_translate_bpm_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranslateBpmRequest"];
      };
    };
    responses: {
      /** @description Translation job started */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AsyncTranslationResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  batch_translate_bpm_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchTranslateBpmRequest"];
      };
    };
    responses: {
      /** @description Batch translation completed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BatchTranslateBpmResponse"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  extract_ir_handler: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TranslateBpmRequest"];
      };
    };
    responses: {
      /** @description IR extraction successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BpmIr"];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_translation_result_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job result retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TranslateBpmResponse"];
        };
      };
      /** @description Job not found or not completed */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_translation_status_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job status retrieved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JobStatusResponse"];
        };
      };
      /** @description Job not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
